@startuml
class Attributes {
    <<internal>> Attributes()
    <<internal>> {static} AdliftModule : string <<get>>
    <<internal>> {static} AdvancedDeepMiningOreScanner : string <<get>>
    <<internal>> {static} AlphaWolfHead : string <<get>>
    <<internal>> {static} AlphaWolfTrophy : string <<get>>
    <<internal>> {static} AluminiumArrow : string <<get>>
    <<internal>> {static} AluminiumBeam : string <<get>>
    <<internal>> {static} AluminiumDoor : string <<get>>
    <<internal>> {static} AluminiumFloor : string <<get>>
    <<internal>> {static} AluminiumFloorTrapdoor : string <<get>>
    <<internal>> {static} AluminiumHalfpieces : string <<get>>
    <<internal>> {static} AluminiumHalfpitches : string <<get>>
    <<internal>> {static} AluminiumIngot : string <<get>>
    <<internal>> {static} AluminiumLadder : string <<get>>
    <<internal>> {static} AluminiumOre : string <<get>>
    <<internal>> {static} AluminiumRailing : string <<get>>
    <<internal>> {static} AluminiumRamp : string <<get>>
    <<internal>> {static} AluminiumRoof : string <<get>>
    <<internal>> {static} AluminiumRoofCorner : string <<get>>
    <<internal>> {static} AluminiumStairs : string <<get>>
    <<internal>> {static} AluminiumTrapdoor : string <<get>>
    <<internal>> {static} AluminiumWall : string <<get>>
    <<internal>> {static} AluminiumWallAngled : string <<get>>
    <<internal>> {static} AluminiumWindow : string <<get>>
    <<internal>> {static} AnimalBait : string <<get>>
    <<internal>> {static} AnimalFat : string <<get>>
    <<internal>> {static} AnimalHealthbarModule : string <<get>>
    <<internal>> {static} AnimalHighlightingModule : string <<get>>
    <<internal>> {static} Anti_ParasiticPaste : string <<get>>
    <<internal>> {static} Anti_ParasiticPill : string <<get>>
    <<internal>> {static} Anti_ParasiticTonic : string <<get>>
    <<internal>> {static} Anti_ParasiticVaccineI : string <<get>>
    <<internal>> {static} Anti_ParasiticVaccineII : string <<get>>
    <<internal>> {static} Anti_ParasiticVaccineIII : string <<get>>
    <<internal>> {static} Anti_PoisonPaste : string <<get>>
    <<internal>> {static} Anti_PoisonPill : string <<get>>
    <<internal>> {static} Anti_PoisonTonic : string <<get>>
    <<internal>> {static} Anti_PoisonVaccineI : string <<get>>
    <<internal>> {static} Anti_PoisonVaccineII : string <<get>>
    <<internal>> {static} Anti_PoisonVaccineIII : string <<get>>
    <<internal>> {static} AntibioticPaste : string <<get>>
    <<internal>> {static} AntibioticPill : string <<get>>
    <<internal>> {static} AntibioticTonic : string <<get>>
    <<internal>> {static} AnvilBench : string <<get>>
    <<internal>> {static} ArchersBackpack : string <<get>>
    <<internal>> {static} BacterialVaccineI : string <<get>>
    <<internal>> {static} BacterialVaccineII : string <<get>>
    <<internal>> {static} BacterialVaccineIII : string <<get>>
    <<internal>> {static} BarbequeCarrot : string <<get>>
    <<internal>> {static} BasicBandage : string <<get>>
    <<internal>> {static} BasicCeilingLight : string <<get>>
    <<internal>> {static} BasicFertilizer : string <<get>>
    <<internal>> {static} BasicWallLight : string <<get>>
    <<internal>> {static} BearHead : string <<get>>
    <<internal>> {static} BearTrophy : string <<get>>
    <<internal>> {static} Bedroll : string <<get>>
    <<internal>> {static} Beer : string <<get>>
    <<internal>> {static} BeerBottle : string <<get>>
    <<internal>> {static} BerryJam : string <<get>>
    <<internal>> {static} Binoculars : string <<get>>
    <<internal>> {static} BiofuelCan : string <<get>>
    <<internal>> {static} BiofuelComposter : string <<get>>
    <<internal>> {static} BiofuelDeep_MiningDrill : string <<get>>
    <<internal>> {static} BiofuelGenerator : string <<get>>
    <<internal>> {static} BiofuelLamp : string <<get>>
    <<internal>> {static} BiofuelStove : string <<get>>
    <<internal>> {static} BlackJaguarHead : string <<get>>
    <<internal>> {static} BlackJaguarTrophy : string <<get>>
    <<internal>> {static} BloodThinningPaste : string <<get>>
    <<internal>> {static} BloodThinningPill : string <<get>>
    <<internal>> {static} BloodThinningTonic : string <<get>>
    <<internal>> {static} BloodThinningVaccineI : string <<get>>
    <<internal>> {static} BloodThinningVaccineII : string <<get>>
    <<internal>> {static} BloodThinningVaccineIII : string <<get>>
    <<internal>> {static} BoltActionRifle : string <<get>>
    <<internal>> {static} Bone : string <<get>>
    <<internal>> {static} BoneArrow : string <<get>>
    <<internal>> {static} BoneKnife : string <<get>>
    <<internal>> {static} BoneSickle : string <<get>>
    <<internal>> {static} BoneSpear : string <<get>>
    <<internal>> {static} Brazier : string <<get>>
    <<internal>> {static} Bread : string <<get>>
    <<internal>> {static} BreadDough : string <<get>>
    <<internal>> {static} BuckshotShell : string <<get>>
    <<internal>> {static} BuffaloHead : string <<get>>
    <<internal>> {static} BuffaloTrophy : string <<get>>
    <<internal>> {static} BuildingUpgradeTool : string <<get>>
    <<internal>> {static} Campfire : string <<get>>
    <<internal>> {static} Canteen : string <<get>>
    <<internal>> {static} CarbonArrow : string <<get>>
    <<internal>> {static} CarbonFiber : string <<get>>
    <<internal>> {static} CarbonPaste : string <<get>>
    <<internal>> {static} CarbonSpear : string <<get>>
    <<internal>> {static} CarpentryBench : string <<get>>
    <<internal>> {static} Carrot : string <<get>>
    <<internal>> {static} CaveScanner : string <<get>>
    <<internal>> {static} CavewormArrow : string <<get>>
    <<internal>> {static} CavewormBow : string <<get>>
    <<internal>> {static} CavewormKnife : string <<get>>
    <<internal>> {static} CavewormSpear : string <<get>>
    <<internal>> {static} CementMixer : string <<get>>
    <<internal>> {static} CharacterCrafting : string <<get>>
    <<internal>> {static} Charcoal : string <<get>>
    <<internal>> {static} CharredCorn : string <<get>>
    <<internal>> {static} ChemistryBench : string <<get>>
    <<internal>> {static} ClothArmsArmor : string <<get>>
    <<internal>> {static} ClothChestArmor : string <<get>>
    <<internal>> {static} ClothFeetArmor : string <<get>>
    <<internal>> {static} ClothHeadArmor : string <<get>>
    <<internal>> {static} ClothLegsArmor : string <<get>>
    <<internal>> {static} CoalOre : string <<get>>
    <<internal>> {static} CocoaSeed : string <<get>>
    <<internal>> {static} CoffeeBean : string <<get>>
    <<internal>> {static} CombatKnife : string <<get>>
    <<internal>> {static} CometCoal : string <<get>>
    <<internal>> {static} CompositeArmsArmor : string <<get>>
    <<internal>> {static} CompositeArrow : string <<get>>
    <<internal>> {static} CompositeChestArmor : string <<get>>
    <<internal>> {static} CompositeFeetArmor : string <<get>>
    <<internal>> {static} CompositeHeadArmor : string <<get>>
    <<internal>> {static} CompositeLegsArmor : string <<get>>
    <<internal>> {static} CompositePaste : string <<get>>
    <<internal>> {static} Composites : string <<get>>
    <<internal>> {static} CompositeSpear : string <<get>>
    <<internal>> {static} CompoundBow : string <<get>>
    <<internal>> {static} ConcreteBeam : string <<get>>
    <<internal>> {static} ConcreteFloor : string <<get>>
    <<internal>> {static} ConcreteFloorTrapdoor : string <<get>>
    <<internal>> {static} ConcreteFrame : string <<get>>
    <<internal>> {static} ConcreteFurnace : string <<get>>
    <<internal>> {static} ConcreteHalfpieces : string <<get>>
    <<internal>> {static} ConcreteHalfpitches : string <<get>>
    <<internal>> {static} ConcreteMix : string <<get>>
    <<internal>> {static} ConcreteRailing : string <<get>>
    <<internal>> {static} ConcreteRamp : string <<get>>
    <<internal>> {static} ConcreteRoof : string <<get>>
    <<internal>> {static} ConcreteRoofCorner : string <<get>>
    <<internal>> {static} ConcreteStairs : string <<get>>
    <<internal>> {static} ConcreteWall : string <<get>>
    <<internal>> {static} ConcreteWallAngled : string <<get>>
    <<internal>> {static} CookedBacon : string <<get>>
    <<internal>> {static} CookedFattyTbone : string <<get>>
    <<internal>> {static} CookedFish : string <<get>>
    <<internal>> {static} CookedGameMeat : string <<get>>
    <<internal>> {static} CookedGiantSteak : string <<get>>
    <<internal>> {static} CookedMeat : string <<get>>
    <<internal>> {static} CookedSoftMeat : string <<get>>
    <<internal>> {static} CookedStringyMeat : string <<get>>
    <<internal>> {static} CookedWhiteMeat : string <<get>>
    <<internal>> {static} CookingStation : string <<get>>
    <<internal>> {static} CoolingBandage : string <<get>>
    <<internal>> {static} CopperBolt : string <<get>>
    <<internal>> {static} CopperIngot : string <<get>>
    <<internal>> {static} CopperNail : string <<get>>
    <<internal>> {static} CopperOre : string <<get>>
    <<internal>> {static} Corn : string <<get>>
    <<internal>> {static} CougarHead : string <<get>>
    <<internal>> {static} CougarTrophy : string <<get>>
    <<internal>> {static} CraftingBench : string <<get>>
    <<internal>> {static} CreamedCorn : string <<get>>
    <<internal>> {static} CrispyBacon : string <<get>>
    <<internal>> {static} Crossbow : string <<get>>
    <<internal>> {static} CrumbedFishFillet : string <<get>>
    <<internal>> {static} CrushedBone : string <<get>>
    <<internal>> {static} CX_400ArmsArmor : string <<get>>
    <<internal>> {static} CX_400ChestArmor : string <<get>>
    <<internal>> {static} CX_400FeetArmor : string <<get>>
    <<internal>> {static} CX_400HeadArmor : string <<get>>
    <<internal>> {static} CX_400LegsArmor : string <<get>>
    <<internal>> {static} DeepMiningOreScanner : string <<get>>
    <<internal>> {static} DeerHead : string <<get>>
    <<internal>> {static} DeerTrophy : string <<get>>
    <<internal>> {static} Dehumidifier : string <<get>>
    <<internal>> {static} DetoxifierModule : string <<get>>
    <<internal>> {static} DirectionalWorklamp : string <<get>>
    <<internal>> {static} DoseupModule : string <<get>>
    <<internal>> {static} DriedFattyTbone : string <<get>>
    <<internal>> {static} DriedGameMeat : string <<get>>
    <<internal>> {static} DriedGiantSteak : string <<get>>
    <<internal>> {static} DriedSoftMeat : string <<get>>
    <<internal>> {static} DriedStringyMeat : string <<get>>
    <<internal>> {static} DriedWhiteMeat : string <<get>>
    <<internal>> {static} DryingRack : string <<get>>
    <<internal>> {static} ElectricCarpentryBench : string <<get>>
    <<internal>> {static} ElectricComposter : string <<get>>
    <<internal>> {static} ElectricDeep_MiningDrill : string <<get>>
    <<internal>> {static} ElectricDehumidifier : string <<get>>
    <<internal>> {static} ElectricFurnace : string <<get>>
    <<internal>> {static} ElectricityTool : string <<get>>
    <<internal>> {static} ElectricMasonryBench : string <<get>>
    <<internal>> {static} Electronics : string <<get>>
    <<internal>> {static} Endurogel : string <<get>>
    <<internal>> {static} Epoxy : string <<get>>
    <<internal>> {static} Exotics : string <<get>>
    <<internal>> {static} Extractor : string <<get>>
    <<internal>> {static} Fabricator : string <<get>>
    <<internal>> {static} Fiber : string <<get>>
    <<internal>> {static} FireArrow : string <<get>>
    <<internal>> {static} FireExtinguisher : string <<get>>
    <<internal>> {static} Firepit : string <<get>>
    <<internal>> {static} Fireplace : string <<get>>
    <<internal>> {static} FireWhacker : string <<get>>
    <<internal>> {static} FishCurry : string <<get>>
    <<internal>> {static} FishingRod : string <<get>>
    <<internal>> {static} FishingTrap : string <<get>>
    <<internal>> {static} FlareArrow : string <<get>>
    <<internal>> {static} Flashlight : string <<get>>
    <<internal>> {static} Flatbread : string <<get>>
    <<internal>> {static} FlatbreadDough : string <<get>>
    <<internal>> {static} FlintArrow : string <<get>>
    <<internal>> {static} FloorTorch : string <<get>>
    <<internal>> {static} Flour : string <<get>>
    <<internal>> {static} FoodConsumptionPaste : string <<get>>
    <<internal>> {static} FragGrenade : string <<get>>
    <<internal>> {static} FrozenRocks : string <<get>>
    <<internal>> {static} FruitPie : string <<get>>
    <<internal>> {static} FruitSalad : string <<get>>
    <<internal>> {static} Fur : string <<get>>
    <<internal>> {static} FurArmsArmor : string <<get>>
    <<internal>> {static} FurChestArmor : string <<get>>
    <<internal>> {static} FurFeetArmor : string <<get>>
    <<internal>> {static} FurHeadArmor : string <<get>>
    <<internal>> {static} FurLegsArmor : string <<get>>
    <<internal>> {static} GatherersBackpack : string <<get>>
    <<internal>> {static} GhillieArmsArmor : string <<get>>
    <<internal>> {static} GhillieChestArmor : string <<get>>
    <<internal>> {static} GhillieFeetArmor : string <<get>>
    <<internal>> {static} GhillieHeadArmor : string <<get>>
    <<internal>> {static} GhillieLegsArmor : string <<get>>
    <<internal>> {static} Glass : string <<get>>
    <<internal>> {static} GlassBeam : string <<get>>
    <<internal>> {static} GlassDoor : string <<get>>
    <<internal>> {static} GlassJar : string <<get>>
    <<internal>> {static} GlassRoof : string <<get>>
    <<internal>> {static} GlassRoofCorner : string <<get>>
    <<internal>> {static} GlassWall : string <<get>>
    <<internal>> {static} GlassWallAngled : string <<get>>
    <<internal>> {static} GlassWindow : string <<get>>
    <<internal>> {static} GlassworkingBench : string <<get>>
    <<internal>> {static} Go : string <<get>>
    <<internal>> {static} GoldOre : string <<get>>
    <<internal>> {static} GorseFlower : string <<get>>
    <<internal>> {static} GorseTea : string <<get>>
    <<internal>> {static} GrilledPumpkin : string <<get>>
    <<internal>> {static} GrowthFertilizer : string <<get>>
    <<internal>> {static} Gunpowder : string <<get>>
    <<internal>> {static} HealingBoostModule : string <<get>>
    <<internal>> {static} HealthBuffPaste : string <<get>>
    <<internal>> {static} HealthRegenerationPaste : string <<get>>
    <<internal>> {static} HealthRestorationPaste : string <<get>>
    <<internal>> {static} HeatBandage : string <<get>>
    <<internal>> {static} HeavyAirConditioner : string <<get>>
    <<internal>> {static} HeavyGlassWindow : string <<get>>
    <<internal>> {static} HeavyHeater : string <<get>>
    <<internal>> {static} HeavyTrapdoor : string <<get>>
    <<internal>> {static} HerbalismBench : string <<get>>
    <<internal>> {static} High_QualityFertilizer : string <<get>>
    <<internal>> {static} HotCocoa : string <<get>>
    <<internal>> {static} HotCoffee : string <<get>>
    <<internal>> {static} HotTea : string <<get>>
    <<internal>> {static} HunterArmsArmor : string <<get>>
    <<internal>> {static} HunterChestArmor : string <<get>>
    <<internal>> {static} HunterFeetArmor : string <<get>>
    <<internal>> {static} HunterHeadArmor : string <<get>>
    <<internal>> {static} HunterLegsArmor : string <<get>>
    <<internal>> {static} HuntingRifle : string <<get>>
    <<internal>> {static} HydroponicCropPlot : string <<get>>
    <<internal>> {static} Ice : string <<get>>
    <<internal>> {static} IceBox : string <<get>>
    <<internal>> {static} InarisArudaArrow : string <<get>>
    <<internal>> {static} InarisDiasAxe : string <<get>>
    <<internal>> {static} InarisGrisSpear : string <<get>>
    <<internal>> {static} InarisNevesPickaxe : string <<get>>
    <<internal>> {static} InarisVenturaKnife : string <<get>>
    <<internal>> {static} IncendiaryRifleRound : string <<get>>
    <<internal>> {static} InteriorWoodBeam : string <<get>>
    <<internal>> {static} InteriorWoodCupboard : string <<get>>
    <<internal>> {static} InteriorWoodDoor : string <<get>>
    <<internal>> {static} InteriorWoodFloor : string <<get>>
    <<internal>> {static} InteriorWoodFloorTrapdoor : string <<get>>
    <<internal>> {static} InteriorWoodHalfpieces : string <<get>>
    <<internal>> {static} InteriorWoodHalfpitches : string <<get>>
    <<internal>> {static} InteriorWoodLadder : string <<get>>
    <<internal>> {static} InteriorWoodRailing : string <<get>>
    <<internal>> {static} InteriorWoodRamp : string <<get>>
    <<internal>> {static} InteriorWoodStairs : string <<get>>
    <<internal>> {static} InteriorWoodTrapdoor : string <<get>>
    <<internal>> {static} InteriorWoodWall : string <<get>>
    <<internal>> {static} InteriorWoodWallAngled : string <<get>>
    <<internal>> {static} IronAxe : string <<get>>
    <<internal>> {static} IronBolt : string <<get>>
    <<internal>> {static} IronCropPlot : string <<get>>
    <<internal>> {static} IronCupboard : string <<get>>
    <<internal>> {static} IronHammer : string <<get>>
    <<internal>> {static} IronIngot : string <<get>>
    <<internal>> {static} IronKnife : string <<get>>
    <<internal>> {static} IronNail : string <<get>>
    <<internal>> {static} IronOre : string <<get>>
    <<internal>> {static} IronPickaxe : string <<get>>
    <<internal>> {static} IronSickle : string <<get>>
    <<internal>> {static} IronSpear : string <<get>>
    <<internal>> {static} JaguarHead : string <<get>>
    <<internal>> {static} JaguarTrophy : string <<get>>
    <<internal>> {static} KickFallModule : string <<get>>
    <<internal>> {static} KitchenBench : string <<get>>
    <<internal>> {static} KitchenStorageBlock : string <<get>>
    <<internal>> {static} Lantern : string <<get>>
    <<internal>> {static} LarkwellMartinezAxe : string <<get>>
    <<internal>> {static} LarkwellMartinezHammer : string <<get>>
    <<internal>> {static} LarkwellMartinezKnife : string <<get>>
    <<internal>> {static} LarkwellMartinezMercenaryBackpack : string <<get>>
    <<internal>> {static} LarkwellMartinezPickaxe : string <<get>>
    <<internal>> {static} LarkwellMartinezSickle : string <<get>>
    <<internal>> {static} LarkwellMartinezSpear : string <<get>>
    <<internal>> {static} LarkwellMartinezTacticalBackpack : string <<get>>
    <<internal>> {static} Leather : string <<get>>
    <<internal>> {static} LeatherArmsArmor : string <<get>>
    <<internal>> {static} LeatherBackpack : string <<get>>
    <<internal>> {static} LeatherChestArmor : string <<get>>
    <<internal>> {static} LeatherCurtainDoor : string <<get>>
    <<internal>> {static} LeatherCurtainWindow : string <<get>>
    <<internal>> {static} LeatherFeetArmor : string <<get>>
    <<internal>> {static} LeatherHeadArmor : string <<get>>
    <<internal>> {static} LeatherLegsArmor : string <<get>>
    <<internal>> {static} LightningRod : string <<get>>
    <<internal>> {static} Lily : string <<get>>
    <<internal>> {static} Longbow : string <<get>>
    <<internal>> {static} LowburnModule : string <<get>>
    <<internal>> {static} Machete : string <<get>>
    <<internal>> {static} MachiningBench : string <<get>>
    <<internal>> {static} MammothHead : string <<get>>
    <<internal>> {static} MammothTrophy : string <<get>>
    <<internal>> {static} MasonryBench : string <<get>>
    <<internal>> {static} MassDampenerModule : string <<get>>
    <<internal>> {static} MaterialProcessor : string <<get>>
    <<internal>> {static} MatureCoconut : string <<get>>
    <<internal>> {static} MeatPie : string <<get>>
    <<internal>> {static} MediumInteriorWoodCrate : string <<get>>
    <<internal>> {static} MediumIronCrate : string <<get>>
    <<internal>> {static} MediumWoodCrate : string <<get>>
    <<internal>> {static} MediumWoodHedgehog : string <<get>>
    <<internal>> {static} MetalOre : string <<get>>
    <<internal>> {static} MetalOxiteDissolver : string <<get>>
    <<internal>> {static} Micromeal : string <<get>>
    <<internal>> {static} MortarandPestle : string <<get>>
    <<internal>> {static} Mushroom : string <<get>>
    <<internal>> {static} MushroomSoup : string <<get>>
    <<internal>> {static} MXCAxe : string <<get>>
    <<internal>> {static} MXCCampfire : string <<get>>
    <<internal>> {static} MXCCrate : string <<get>>
    <<internal>> {static} MXCFirewhacker : string <<get>>
    <<internal>> {static} MXCFlangeArrow : string <<get>>
    <<internal>> {static} MXCFurnace : string <<get>>
    <<internal>> {static} MXCHammer : string <<get>>
    <<internal>> {static} MXCKnife : string <<get>>
    <<internal>> {static} MXCNerveArrow : string <<get>>
    <<internal>> {static} MXCPickaxe : string <<get>>
    <<internal>> {static} MXCSickle : string <<get>>
    <<internal>> {static} MXCSpear : string <<get>>
    <<internal>> {static} MXCVenomArrow : string <<get>>
    <<internal>> {static} NaneoArmsArmor : string <<get>>
    <<internal>> {static} NaneoChestArmor : string <<get>>
    <<internal>> {static} NaneoFeetArmor : string <<get>>
    <<internal>> {static} NaneoHeadArmor : string <<get>>
    <<internal>> {static} NaneoLegsArmor : string <<get>>
    <<internal>> {static} OmnidirectionalWorklamp : string <<get>>
    <<internal>> {static} OrganicResin : string <<get>>
    <<internal>> {static} Oxidizer : string <<get>>
    <<internal>> {static} Oxite : string <<get>>
    <<internal>> {static} OxiteDissolver : string <<get>>
    <<internal>> {static} Oxygel : string <<get>>
    <<internal>> {static} OxygenBladder : string <<get>>
    <<internal>> {static} OxygenBuffPaste : string <<get>>
    <<internal>> {static} OxygenConsumptionPaste : string <<get>>
    <<internal>> {static} OxygenRestorationPaste : string <<get>>
    <<internal>> {static} OxygenTank : string <<get>>
    <<internal>> {static} Pastry : string <<get>>
    <<internal>> {static} PatcherIIModule : string <<get>>
    <<internal>> {static} PatcherIModule : string <<get>>
    <<internal>> {static} PickledCarrot : string <<get>>
    <<internal>> {static} Pistol : string <<get>>
    <<internal>> {static} PistolRound : string <<get>>
    <<internal>> {static} PlatinumAxe : string <<get>>
    <<internal>> {static} PlatinumBolt : string <<get>>
    <<internal>> {static} PlatinumHammer : string <<get>>
    <<internal>> {static} PlatinumIngot : string <<get>>
    <<internal>> {static} PlatinumKnife : string <<get>>
    <<internal>> {static} PlatinumOre : string <<get>>
    <<internal>> {static} PlatinumPickaxe : string <<get>>
    <<internal>> {static} PlatinumSickle : string <<get>>
    <<internal>> {static} PlatinumSpear : string <<get>>
    <<internal>> {static} PlayerTrackerModule : string <<get>>
    <<internal>> {static} PoisonArrow : string <<get>>
    <<internal>> {static} PoisonedAnimalBait : string <<get>>
    <<internal>> {static} PoisonPaste : string <<get>>
    <<internal>> {static} PoisonSack : string <<get>>
    <<internal>> {static} PolarBearArmsArmor : string <<get>>
    <<internal>> {static} PolarBearChestArmor : string <<get>>
    <<internal>> {static} PolarBearFeetArmor : string <<get>>
    <<internal>> {static} PolarBearHead : string <<get>>
    <<internal>> {static} PolarBearHeadArmor : string <<get>>
    <<internal>> {static} PolarBearLegsArmor : string <<get>>
    <<internal>> {static} PolarBearPelt : string <<get>>
    <<internal>> {static} PolarBearTrophy : string <<get>>
    <<internal>> {static} PortableBeacon : string <<get>>
    <<internal>> {static} PotbellyStove : string <<get>>
    <<internal>> {static} Pumpkin : string <<get>>
    <<internal>> {static} PumpkinBread : string <<get>>
    <<internal>> {static} Radar : string <<get>>
    <<internal>> {static} RainReservoir : string <<get>>
    <<internal>> {static} RawBacon : string <<get>>
    <<internal>> {static} RawFattyTbone : string <<get>>
    <<internal>> {static} RawFish : string <<get>>
    <<internal>> {static} RawGameMeat : string <<get>>
    <<internal>> {static} RawGiantSteak : string <<get>>
    <<internal>> {static} RawMeat : string <<get>>
    <<internal>> {static} RawSoftMeat : string <<get>>
    <<internal>> {static} RawStringyMeat : string <<get>>
    <<internal>> {static} RawWhiteMeat : string <<get>>
    <<internal>> {static} RecurveBow : string <<get>>
    <<internal>> {static} ReedFlower : string <<get>>
    <<internal>> {static} RefinedGold : string <<get>>
    <<internal>> {static} RefinedWood : string <<get>>
    <<internal>> {static} Refrigerator : string <<get>>
    <<internal>> {static} ReinforcedDoor : string <<get>>
    <<internal>> {static} ReinforcedLadder : string <<get>>
    <<internal>> {static} ReinforcedRailing : string <<get>>
    <<internal>> {static} ReinforcedTrapdoor : string <<get>>
    <<internal>> {static} ReinforcedWindow : string <<get>>
    <<internal>> {static} Resources : string <<get>>
    <<internal>> {static} RifleRound : string <<get>>
    <<internal>> {static} RipeCoconut : string <<get>>
    <<internal>> {static} RoastSquash : string <<get>>
    <<internal>> {static} RoastVegetables : string <<get>>
    <<internal>> {static} Rope : string <<get>>
    <<internal>> {static} SandwormArrow : string <<get>>
    <<internal>> {static} SandwormBow : string <<get>>
    <<internal>> {static} SandwormKnife : string <<get>>
    <<internal>> {static} SandwormScale : string <<get>>
    <<internal>> {static} SandwormSpear : string <<get>>
    <<internal>> {static} ScorpionHedgehog : string <<get>>
    <<internal>> {static} ScorpionPincerTrap : string <<get>>
    <<internal>> {static} ShengongAkiraHammer : string <<get>>
    <<internal>> {static} ShengongDaokouKnife : string <<get>>
    <<internal>> {static} ShengongDidaSpear : string <<get>>
    <<internal>> {static} ShengongDongPickaxe : string <<get>>
    <<internal>> {static} ShengongGongBuSpear : string <<get>>
    <<internal>> {static} ShengongHeikeAxe : string <<get>>
    <<internal>> {static} ShengongHuluCanteen : string <<get>>
    <<internal>> {static} ShengongJiBow : string <<get>>
    <<internal>> {static} ShengongJijingBow : string <<get>>
    <<internal>> {static} ShengongJijuSpear : string <<get>>
    <<internal>> {static} ShengongJushiPickaxe : string <<get>>
    <<internal>> {static} ShengongKuangPickaxe : string <<get>>
    <<internal>> {static} ShengongLieAxe : string <<get>>
    <<internal>> {static} ShengongLiweiO2Tank : string <<get>>
    <<internal>> {static} ShengongQieKnife : string <<get>>
    <<internal>> {static} ShengongSenAxe : string <<get>>
    <<internal>> {static} ShengongShuiKnife : string <<get>>
    <<internal>> {static} ShengongSichouKnife : string <<get>>
    <<internal>> {static} ShengongSuiShiPickaxe : string <<get>>
    <<internal>> {static} ShengongTetsuoHammer : string <<get>>
    <<internal>> {static} ShengongWenheArrow : string <<get>>
    <<internal>> {static} ShengongXingxingSpear : string <<get>>
    <<internal>> {static} ShengongYeyingBandage : string <<get>>
    <<internal>> {static} ShengongZhangHuBow : string <<get>>
    <<internal>> {static} Shotgun : string <<get>>
    <<internal>> {static} Shovel : string <<get>>
    <<internal>> {static} SilicaOre : string <<get>>
    <<internal>> {static} SkinningBench : string <<get>>
    <<internal>> {static} SmallInteriorWoodCrate : string <<get>>
    <<internal>> {static} SmallIronCrate : string <<get>>
    <<internal>> {static} SmallWoodCrate : string <<get>>
    <<internal>> {static} SmallWoodSign : string <<get>>
    <<internal>> {static} SmokeGrenade : string <<get>>
    <<internal>> {static} SnowLeopardHead : string <<get>>
    <<internal>> {static} SnowLeopardTrophy : string <<get>>
    <<internal>> {static} SolarPanel : string <<get>>
    <<internal>> {static} SoyBean : string <<get>>
    <<internal>> {static} SoyBeanStir_Fry : string <<get>>
    <<internal>> {static} Splint : string <<get>>
    <<internal>> {static} SpoiledMeat : string <<get>>
    <<internal>> {static} SpoiledPlants : string <<get>>
    <<internal>> {static} Sponge : string <<get>>
    <<internal>> {static} Squash : string <<get>>
    <<internal>> {static} ST_700ArmsArmor : string <<get>>
    <<internal>> {static} ST_700ChestArmor : string <<get>>
    <<internal>> {static} ST_700FeetArmor : string <<get>>
    <<internal>> {static} ST_700HeadArmor : string <<get>>
    <<internal>> {static} ST_700LegsArmor : string <<get>>
    <<internal>> {static} Stamina : string <<get>>
    <<internal>> {static} StaminaBuffPaste : string <<get>>
    <<internal>> {static} StaminaConsumptionPaste : string <<get>>
    <<internal>> {static} StaminaRegenerationPaste : string <<get>>
    <<internal>> {static} StaminaRestorationPaste : string <<get>>
    <<internal>> {static} SteelAxe : string <<get>>
    <<internal>> {static} SteelBloom : string <<get>>
    <<internal>> {static} SteelBolt : string <<get>>
    <<internal>> {static} SteelHammer : string <<get>>
    <<internal>> {static} SteelIngot : string <<get>>
    <<internal>> {static} SteelKnife : string <<get>>
    <<internal>> {static} SteelPickaxe : string <<get>>
    <<internal>> {static} SteelRebar : string <<get>>
    <<internal>> {static} SteelScrew : string <<get>>
    <<internal>> {static} SteelSpear : string <<get>>
    <<internal>> {static} Stew : string <<get>>
    <<internal>> {static} Stick : string <<get>>
    <<internal>> {static} Stone : string <<get>>
    <<internal>> {static} StoneArrow : string <<get>>
    <<internal>> {static} StoneAxe : string <<get>>
    <<internal>> {static} StoneBeam : string <<get>>
    <<internal>> {static} StoneFloor : string <<get>>
    <<internal>> {static} StoneFloorTrapdoor : string <<get>>
    <<internal>> {static} StoneFrame : string <<get>>
    <<internal>> {static} StoneFurnace : string <<get>>
    <<internal>> {static} StoneHalfpieces : string <<get>>
    <<internal>> {static} StoneHalfpitches : string <<get>>
    <<internal>> {static} StoneKnife : string <<get>>
    <<internal>> {static} StonePickaxe : string <<get>>
    <<internal>> {static} StonePile : string <<get>>
    <<internal>> {static} StoneRamp : string <<get>>
    <<internal>> {static} StoneRoof : string <<get>>
    <<internal>> {static} StoneRoofCorner : string <<get>>
    <<internal>> {static} StoneStairs : string <<get>>
    <<internal>> {static} StoneWall : string <<get>>
    <<internal>> {static} StoneWallAngled : string <<get>>
    <<internal>> {static} StrengthBoostModule : string <<get>>
    <<internal>> {static} Sulfur : string <<get>>
    <<internal>> {static} SurvivalBackpack : string <<get>>
    <<internal>> {static} SutureKit : string <<get>>
    <<internal>> {static} SweetcornSoup : string <<get>>
    <<internal>> {static} TaxidermyKnife : string <<get>>
    <<internal>> {static} Tea : string <<get>>
    <<internal>> {static} TextilesBench : string <<get>>
    <<internal>> {static} ThatchBeam : string <<get>>
    <<internal>> {static} ThatchDoor : string <<get>>
    <<internal>> {static} ThatchFloor : string <<get>>
    <<internal>> {static} ThatchFloorTrapdoor : string <<get>>
    <<internal>> {static} ThatchHalfpieces : string <<get>>
    <<internal>> {static} ThatchHalfpitches : string <<get>>
    <<internal>> {static} ThatchLadder : string <<get>>
    <<internal>> {static} ThatchRailing : string <<get>>
    <<internal>> {static} ThatchRamp : string <<get>>
    <<internal>> {static} ThatchRoof : string <<get>>
    <<internal>> {static} ThatchRoofCorner : string <<get>>
    <<internal>> {static} ThatchStairs : string <<get>>
    <<internal>> {static} ThatchTrapdoor : string <<get>>
    <<internal>> {static} ThatchWall : string <<get>>
    <<internal>> {static} ThatchWallAngled : string <<get>>
    <<internal>> {static} ThatchWindow : string <<get>>
    <<internal>> {static} Thermos : string <<get>>
    <<internal>> {static} TitaniumArrow : string <<get>>
    <<internal>> {static} TitaniumAxe : string <<get>>
    <<internal>> {static} TitaniumBolt : string <<get>>
    <<internal>> {static} TitaniumHammer : string <<get>>
    <<internal>> {static} TitaniumIngot : string <<get>>
    <<internal>> {static} TitaniumKnife : string <<get>>
    <<internal>> {static} TitaniumOre : string <<get>>
    <<internal>> {static} TitaniumPickaxe : string <<get>>
    <<internal>> {static} TitaniumSickle : string <<get>>
    <<internal>> {static} TitaniumSpear : string <<get>>
    <<internal>> {static} TreeSap : string <<get>>
    <<internal>> {static} TrophyBench : string <<get>>
    <<internal>> {static} Ultrameal : string <<get>>
    <<internal>> {static} VegetablePie : string <<get>>
    <<internal>> {static} WallTorch : string <<get>>
    <<internal>> {static} Water : string <<get>>
    <<internal>> {static} WaterConsumptionPaste : string <<get>>
    <<internal>> {static} Watermelon : string <<get>>
    <<internal>> {static} WaterPipeTool : string <<get>>
    <<internal>> {static} WaterPump : string <<get>>
    <<internal>> {static} Waterskin : string <<get>>
    <<internal>> {static} WaterSources : string <<get>>
    <<internal>> {static} WaterSprinkler : string <<get>>
    <<internal>> {static} Wheat : string <<get>>
    <<internal>> {static} WildBerry : string <<get>>
    <<internal>> {static} WildSalad : string <<get>>
    <<internal>> {static} Wine : string <<get>>
    <<internal>> {static} WineBottle : string <<get>>
    <<internal>> {static} Wood : string <<get>>
    <<internal>> {static} WoodBeam : string <<get>>
    <<internal>> {static} WoodBed : string <<get>>
    <<internal>> {static} WoodBow : string <<get>>
    <<internal>> {static} WoodChair : string <<get>>
    <<internal>> {static} WoodComposter : string <<get>>
    <<internal>> {static} WoodCropPlot : string <<get>>
    <<internal>> {static} WoodCupboard : string <<get>>
    <<internal>> {static} WoodDoor : string <<get>>
    <<internal>> {static} WoodFloor : string <<get>>
    <<internal>> {static} WoodFloorTrapdoor : string <<get>>
    <<internal>> {static} WoodHalfpieces : string <<get>>
    <<internal>> {static} WoodHalfpitches : string <<get>>
    <<internal>> {static} WoodLadder : string <<get>>
    <<internal>> {static} WoodPile : string <<get>>
    <<internal>> {static} WoodRagTorch : string <<get>>
    <<internal>> {static} WoodRailing : string <<get>>
    <<internal>> {static} WoodRamp : string <<get>>
    <<internal>> {static} WoodRepairHammer : string <<get>>
    <<internal>> {static} WoodRoof : string <<get>>
    <<internal>> {static} WoodRoofCorner : string <<get>>
    <<internal>> {static} WoodSpear : string <<get>>
    <<internal>> {static} WoodStairs : string <<get>>
    <<internal>> {static} WoodTable : string <<get>>
    <<internal>> {static} WoodTorch : string <<get>>
    <<internal>> {static} WoodTrapdoor : string <<get>>
    <<internal>> {static} WoodWall : string <<get>>
    <<internal>> {static} WoodWallAngled : string <<get>>
    <<internal>> {static} WoodWindow : string <<get>>
    <<internal>> {static} WorkShop : string <<get>>
    <<internal>> {static} WorkshopRepairKit : string <<get>>
    <<internal>> {static} WorkshopRepairKitBundle : string <<get>>
    <<internal>> {static} WormScale : string <<get>>
    <<internal>> {static} Yeast : string <<get>>
    <<internal>> {static} YoungCoconut : string <<get>>
}
@enduml
