@startuml
class ObjectNames {
    <<internal>> ObjectNames()
    + {static} AdliftModule : string <<get>>
    + {static} AdvancedDeepMiningOreScanner : string <<get>>
    + {static} AlphaWolfHead : string <<get>>
    + {static} AlphaWolfTrophy : string <<get>>
    + {static} AluminiumArrow : string <<get>>
    + {static} AluminiumBeam : string <<get>>
    + {static} AluminiumDoor : string <<get>>
    + {static} AluminiumFloor : string <<get>>
    + {static} AluminiumFloorTrapdoor : string <<get>>
    + {static} AluminiumHalfpieces : string <<get>>
    + {static} AluminiumHalfpitches : string <<get>>
    + {static} AluminiumIngot : string <<get>>
    + {static} AluminiumLadder : string <<get>>
    + {static} AluminiumOre : string <<get>>
    + {static} AluminiumRailing : string <<get>>
    + {static} AluminiumRamp : string <<get>>
    + {static} AluminiumRoof : string <<get>>
    + {static} AluminiumRoofCorner : string <<get>>
    + {static} AluminiumStairs : string <<get>>
    + {static} AluminiumTrapdoor : string <<get>>
    + {static} AluminiumWall : string <<get>>
    + {static} AluminiumWallAngled : string <<get>>
    + {static} AluminiumWindow : string <<get>>
    + {static} AnimalBait : string <<get>>
    + {static} AnimalFat : string <<get>>
    + {static} AnimalHealthbarModule : string <<get>>
    + {static} AnimalHighlightingModule : string <<get>>
    + {static} Anti_ParasiticPaste : string <<get>>
    + {static} Anti_ParasiticPill : string <<get>>
    + {static} Anti_ParasiticTonic : string <<get>>
    + {static} Anti_ParasiticVaccineI : string <<get>>
    + {static} Anti_ParasiticVaccineII : string <<get>>
    + {static} Anti_ParasiticVaccineIII : string <<get>>
    + {static} Anti_PoisonPaste : string <<get>>
    + {static} Anti_PoisonPill : string <<get>>
    + {static} Anti_PoisonTonic : string <<get>>
    + {static} Anti_PoisonVaccineI : string <<get>>
    + {static} Anti_PoisonVaccineII : string <<get>>
    + {static} Anti_PoisonVaccineIII : string <<get>>
    + {static} AntibioticPaste : string <<get>>
    + {static} AntibioticPill : string <<get>>
    + {static} AntibioticTonic : string <<get>>
    + {static} AnvilBench : string <<get>>
    + {static} ArchersBackpack : string <<get>>
    + {static} BacterialVaccineI : string <<get>>
    + {static} BacterialVaccineII : string <<get>>
    + {static} BacterialVaccineIII : string <<get>>
    + {static} BarbequeCarrot : string <<get>>
    + {static} BasicBandage : string <<get>>
    + {static} BasicCeilingLight : string <<get>>
    + {static} BasicFertilizer : string <<get>>
    + {static} BasicWallLight : string <<get>>
    + {static} BearHead : string <<get>>
    + {static} BearTrophy : string <<get>>
    + {static} Bedroll : string <<get>>
    + {static} Beer : string <<get>>
    + {static} BeerBottle : string <<get>>
    + {static} BerryJam : string <<get>>
    + {static} Binoculars : string <<get>>
    + {static} BiofuelCan : string <<get>>
    + {static} BiofuelComposter : string <<get>>
    + {static} BiofuelDeep_MiningDrill : string <<get>>
    + {static} BiofuelGenerator : string <<get>>
    + {static} BiofuelLamp : string <<get>>
    + {static} BiofuelStove : string <<get>>
    + {static} BlackJaguarHead : string <<get>>
    + {static} BlackJaguarTrophy : string <<get>>
    + {static} BloodThinningPaste : string <<get>>
    + {static} BloodThinningPill : string <<get>>
    + {static} BloodThinningTonic : string <<get>>
    + {static} BloodThinningVaccineI : string <<get>>
    + {static} BloodThinningVaccineII : string <<get>>
    + {static} BloodThinningVaccineIII : string <<get>>
    + {static} BoltActionRifle : string <<get>>
    + {static} Bone : string <<get>>
    + {static} BoneArrow : string <<get>>
    + {static} BoneKnife : string <<get>>
    + {static} BoneSickle : string <<get>>
    + {static} BoneSpear : string <<get>>
    + {static} Brazier : string <<get>>
    + {static} Bread : string <<get>>
    + {static} BreadDough : string <<get>>
    + {static} BuckshotShell : string <<get>>
    + {static} BuffaloHead : string <<get>>
    + {static} BuffaloTrophy : string <<get>>
    + {static} BuildingUpgradeTool : string <<get>>
    + {static} Campfire : string <<get>>
    + {static} Canteen : string <<get>>
    + {static} CarbonArrow : string <<get>>
    + {static} CarbonFiber : string <<get>>
    + {static} CarbonPaste : string <<get>>
    + {static} CarbonSpear : string <<get>>
    + {static} CarpentryBench : string <<get>>
    + {static} Carrot : string <<get>>
    + {static} CaveScanner : string <<get>>
    + {static} CavewormArrow : string <<get>>
    + {static} CavewormBow : string <<get>>
    + {static} CavewormKnife : string <<get>>
    + {static} CavewormSpear : string <<get>>
    + {static} CementMixer : string <<get>>
    + {static} CharacterCrafting : string <<get>>
    + {static} Charcoal : string <<get>>
    + {static} CharredCorn : string <<get>>
    + {static} ChemistryBench : string <<get>>
    + {static} ClothArmsArmor : string <<get>>
    + {static} ClothChestArmor : string <<get>>
    + {static} ClothFeetArmor : string <<get>>
    + {static} ClothHeadArmor : string <<get>>
    + {static} ClothLegsArmor : string <<get>>
    + {static} CoalOre : string <<get>>
    + {static} CocoaSeed : string <<get>>
    + {static} CoffeeBean : string <<get>>
    + {static} CombatKnife : string <<get>>
    + {static} CometCoal : string <<get>>
    + {static} CompositeArmsArmor : string <<get>>
    + {static} CompositeArrow : string <<get>>
    + {static} CompositeChestArmor : string <<get>>
    + {static} CompositeFeetArmor : string <<get>>
    + {static} CompositeHeadArmor : string <<get>>
    + {static} CompositeLegsArmor : string <<get>>
    + {static} CompositePaste : string <<get>>
    + {static} Composites : string <<get>>
    + {static} CompositeSpear : string <<get>>
    + {static} CompoundBow : string <<get>>
    + {static} ConcreteBeam : string <<get>>
    + {static} ConcreteFloor : string <<get>>
    + {static} ConcreteFloorTrapdoor : string <<get>>
    + {static} ConcreteFrame : string <<get>>
    + {static} ConcreteFurnace : string <<get>>
    + {static} ConcreteHalfpieces : string <<get>>
    + {static} ConcreteHalfpitches : string <<get>>
    + {static} ConcreteMix : string <<get>>
    + {static} ConcreteRailing : string <<get>>
    + {static} ConcreteRamp : string <<get>>
    + {static} ConcreteRoof : string <<get>>
    + {static} ConcreteRoofCorner : string <<get>>
    + {static} ConcreteStairs : string <<get>>
    + {static} ConcreteWall : string <<get>>
    + {static} ConcreteWallAngled : string <<get>>
    + {static} CookedBacon : string <<get>>
    + {static} CookedFattyTbone : string <<get>>
    + {static} CookedFish : string <<get>>
    + {static} CookedGameMeat : string <<get>>
    + {static} CookedGiantSteak : string <<get>>
    + {static} CookedMeat : string <<get>>
    + {static} CookedSoftMeat : string <<get>>
    + {static} CookedStringyMeat : string <<get>>
    + {static} CookedWhiteMeat : string <<get>>
    + {static} CookingStation : string <<get>>
    + {static} CoolingBandage : string <<get>>
    + {static} CopperBolt : string <<get>>
    + {static} CopperIngot : string <<get>>
    + {static} CopperNail : string <<get>>
    + {static} CopperOre : string <<get>>
    + {static} Corn : string <<get>>
    + {static} CougarHead : string <<get>>
    + {static} CougarTrophy : string <<get>>
    + {static} CraftingBench : string <<get>>
    + {static} CreamedCorn : string <<get>>
    + {static} CrispyBacon : string <<get>>
    + {static} Crossbow : string <<get>>
    + {static} CrumbedFishFillet : string <<get>>
    + {static} CrushedBone : string <<get>>
    + {static} CX_400ArmsArmor : string <<get>>
    + {static} CX_400ChestArmor : string <<get>>
    + {static} CX_400FeetArmor : string <<get>>
    + {static} CX_400HeadArmor : string <<get>>
    + {static} CX_400LegsArmor : string <<get>>
    + {static} DeepMiningOreScanner : string <<get>>
    + {static} DeerHead : string <<get>>
    + {static} DeerTrophy : string <<get>>
    + {static} Dehumidifier : string <<get>>
    + {static} DetoxifierModule : string <<get>>
    + {static} DirectionalWorklamp : string <<get>>
    + {static} DoseupModule : string <<get>>
    + {static} DriedFattyTbone : string <<get>>
    + {static} DriedGameMeat : string <<get>>
    + {static} DriedGiantSteak : string <<get>>
    + {static} DriedSoftMeat : string <<get>>
    + {static} DriedStringyMeat : string <<get>>
    + {static} DriedWhiteMeat : string <<get>>
    + {static} DryingRack : string <<get>>
    + {static} ElectricCarpentryBench : string <<get>>
    + {static} ElectricComposter : string <<get>>
    + {static} ElectricDeep_MiningDrill : string <<get>>
    + {static} ElectricDehumidifier : string <<get>>
    + {static} ElectricFurnace : string <<get>>
    + {static} ElectricityTool : string <<get>>
    + {static} ElectricMasonryBench : string <<get>>
    + {static} Electronics : string <<get>>
    + {static} Endurogel : string <<get>>
    + {static} Epoxy : string <<get>>
    + {static} Exotics : string <<get>>
    + {static} Extractor : string <<get>>
    + {static} Fabricator : string <<get>>
    + {static} Fiber : string <<get>>
    + {static} FireArrow : string <<get>>
    + {static} FireExtinguisher : string <<get>>
    + {static} Firepit : string <<get>>
    + {static} Fireplace : string <<get>>
    + {static} FireWhacker : string <<get>>
    + {static} FishCurry : string <<get>>
    + {static} FishingRod : string <<get>>
    + {static} FishingTrap : string <<get>>
    + {static} FlareArrow : string <<get>>
    + {static} Flashlight : string <<get>>
    + {static} Flatbread : string <<get>>
    + {static} FlatbreadDough : string <<get>>
    + {static} FlintArrow : string <<get>>
    + {static} FloorTorch : string <<get>>
    + {static} Flour : string <<get>>
    + {static} FoodConsumptionPaste : string <<get>>
    + {static} FragGrenade : string <<get>>
    + {static} FrozenRocks : string <<get>>
    + {static} FruitPie : string <<get>>
    + {static} FruitSalad : string <<get>>
    + {static} Fur : string <<get>>
    + {static} FurArmsArmor : string <<get>>
    + {static} FurChestArmor : string <<get>>
    + {static} FurFeetArmor : string <<get>>
    + {static} FurHeadArmor : string <<get>>
    + {static} FurLegsArmor : string <<get>>
    + {static} GatherersBackpack : string <<get>>
    + {static} GhillieArmsArmor : string <<get>>
    + {static} GhillieChestArmor : string <<get>>
    + {static} GhillieFeetArmor : string <<get>>
    + {static} GhillieHeadArmor : string <<get>>
    + {static} GhillieLegsArmor : string <<get>>
    + {static} Glass : string <<get>>
    + {static} GlassBeam : string <<get>>
    + {static} GlassDoor : string <<get>>
    + {static} GlassJar : string <<get>>
    + {static} GlassRoof : string <<get>>
    + {static} GlassRoofCorner : string <<get>>
    + {static} GlassWall : string <<get>>
    + {static} GlassWallAngled : string <<get>>
    + {static} GlassWindow : string <<get>>
    + {static} GlassworkingBench : string <<get>>
    + {static} Go : string <<get>>
    + {static} GoldOre : string <<get>>
    + {static} GorseFlower : string <<get>>
    + {static} GorseTea : string <<get>>
    + {static} GrilledPumpkin : string <<get>>
    + {static} GrowthFertilizer : string <<get>>
    + {static} Gunpowder : string <<get>>
    + {static} HealingBoostModule : string <<get>>
    + {static} HealthBuffPaste : string <<get>>
    + {static} HealthRegenerationPaste : string <<get>>
    + {static} HealthRestorationPaste : string <<get>>
    + {static} HeatBandage : string <<get>>
    + {static} HeavyAirConditioner : string <<get>>
    + {static} HeavyGlassWindow : string <<get>>
    + {static} HeavyHeater : string <<get>>
    + {static} HeavyTrapdoor : string <<get>>
    + {static} HerbalismBench : string <<get>>
    + {static} High_QualityFertilizer : string <<get>>
    + {static} HotCocoa : string <<get>>
    + {static} HotCoffee : string <<get>>
    + {static} HotTea : string <<get>>
    + {static} HunterArmsArmor : string <<get>>
    + {static} HunterChestArmor : string <<get>>
    + {static} HunterFeetArmor : string <<get>>
    + {static} HunterHeadArmor : string <<get>>
    + {static} HunterLegsArmor : string <<get>>
    + {static} HuntingRifle : string <<get>>
    + {static} HydroponicCropPlot : string <<get>>
    + {static} Ice : string <<get>>
    + {static} IceBox : string <<get>>
    + {static} InarisArudaArrow : string <<get>>
    + {static} InarisDiasAxe : string <<get>>
    + {static} InarisGrisSpear : string <<get>>
    + {static} InarisNevesPickaxe : string <<get>>
    + {static} InarisVenturaKnife : string <<get>>
    + {static} IncendiaryRifleRound : string <<get>>
    + {static} InteriorWoodBeam : string <<get>>
    + {static} InteriorWoodCupboard : string <<get>>
    + {static} InteriorWoodDoor : string <<get>>
    + {static} InteriorWoodFloor : string <<get>>
    + {static} InteriorWoodFloorTrapdoor : string <<get>>
    + {static} InteriorWoodHalfpieces : string <<get>>
    + {static} InteriorWoodHalfpitches : string <<get>>
    + {static} InteriorWoodLadder : string <<get>>
    + {static} InteriorWoodRailing : string <<get>>
    + {static} InteriorWoodRamp : string <<get>>
    + {static} InteriorWoodStairs : string <<get>>
    + {static} InteriorWoodTrapdoor : string <<get>>
    + {static} InteriorWoodWall : string <<get>>
    + {static} InteriorWoodWallAngled : string <<get>>
    + {static} IronAxe : string <<get>>
    + {static} IronBolt : string <<get>>
    + {static} IronCropPlot : string <<get>>
    + {static} IronCupboard : string <<get>>
    + {static} IronHammer : string <<get>>
    + {static} IronIngot : string <<get>>
    + {static} IronKnife : string <<get>>
    + {static} IronNail : string <<get>>
    + {static} IronOre : string <<get>>
    + {static} IronPickaxe : string <<get>>
    + {static} IronSickle : string <<get>>
    + {static} IronSpear : string <<get>>
    + {static} JaguarHead : string <<get>>
    + {static} JaguarTrophy : string <<get>>
    + {static} KickFallModule : string <<get>>
    + {static} KitchenBench : string <<get>>
    + {static} KitchenStorageBlock : string <<get>>
    + {static} Lantern : string <<get>>
    + {static} LarkwellMartinezAxe : string <<get>>
    + {static} LarkwellMartinezHammer : string <<get>>
    + {static} LarkwellMartinezKnife : string <<get>>
    + {static} LarkwellMartinezMercenaryBackpack : string <<get>>
    + {static} LarkwellMartinezPickaxe : string <<get>>
    + {static} LarkwellMartinezSickle : string <<get>>
    + {static} LarkwellMartinezSpear : string <<get>>
    + {static} LarkwellMartinezTacticalBackpack : string <<get>>
    + {static} Leather : string <<get>>
    + {static} LeatherArmsArmor : string <<get>>
    + {static} LeatherBackpack : string <<get>>
    + {static} LeatherChestArmor : string <<get>>
    + {static} LeatherCurtainDoor : string <<get>>
    + {static} LeatherCurtainWindow : string <<get>>
    + {static} LeatherFeetArmor : string <<get>>
    + {static} LeatherHeadArmor : string <<get>>
    + {static} LeatherLegsArmor : string <<get>>
    + {static} LightningRod : string <<get>>
    + {static} Lily : string <<get>>
    + {static} Longbow : string <<get>>
    + {static} LowburnModule : string <<get>>
    + {static} Machete : string <<get>>
    + {static} MachiningBench : string <<get>>
    + {static} MammothHead : string <<get>>
    + {static} MammothTrophy : string <<get>>
    + {static} MasonryBench : string <<get>>
    + {static} MassDampenerModule : string <<get>>
    + {static} MaterialProcessor : string <<get>>
    + {static} MatureCoconut : string <<get>>
    + {static} MeatPie : string <<get>>
    + {static} MediumInteriorWoodCrate : string <<get>>
    + {static} MediumIronCrate : string <<get>>
    + {static} MediumWoodCrate : string <<get>>
    + {static} MediumWoodHedgehog : string <<get>>
    + {static} MetalOre : string <<get>>
    + {static} MetalOxiteDissolver : string <<get>>
    + {static} Micromeal : string <<get>>
    + {static} MortarandPestle : string <<get>>
    + {static} Mushroom : string <<get>>
    + {static} MushroomSoup : string <<get>>
    + {static} MXCAxe : string <<get>>
    + {static} MXCCampfire : string <<get>>
    + {static} MXCCrate : string <<get>>
    + {static} MXCFirewhacker : string <<get>>
    + {static} MXCFlangeArrow : string <<get>>
    + {static} MXCFurnace : string <<get>>
    + {static} MXCHammer : string <<get>>
    + {static} MXCKnife : string <<get>>
    + {static} MXCNerveArrow : string <<get>>
    + {static} MXCPickaxe : string <<get>>
    + {static} MXCSickle : string <<get>>
    + {static} MXCSpear : string <<get>>
    + {static} MXCVenomArrow : string <<get>>
    + {static} NaneoArmsArmor : string <<get>>
    + {static} NaneoChestArmor : string <<get>>
    + {static} NaneoFeetArmor : string <<get>>
    + {static} NaneoHeadArmor : string <<get>>
    + {static} NaneoLegsArmor : string <<get>>
    + {static} OmnidirectionalWorklamp : string <<get>>
    + {static} OrganicResin : string <<get>>
    + {static} Oxidizer : string <<get>>
    + {static} Oxite : string <<get>>
    + {static} OxiteDissolver : string <<get>>
    + {static} Oxygel : string <<get>>
    + {static} OxygenBladder : string <<get>>
    + {static} OxygenBuffPaste : string <<get>>
    + {static} OxygenConsumptionPaste : string <<get>>
    + {static} OxygenRestorationPaste : string <<get>>
    + {static} OxygenTank : string <<get>>
    + {static} Pastry : string <<get>>
    + {static} PatcherIIModule : string <<get>>
    + {static} PatcherIModule : string <<get>>
    + {static} PickledCarrot : string <<get>>
    + {static} Pistol : string <<get>>
    + {static} PistolRound : string <<get>>
    + {static} PlatinumAxe : string <<get>>
    + {static} PlatinumBolt : string <<get>>
    + {static} PlatinumHammer : string <<get>>
    + {static} PlatinumIngot : string <<get>>
    + {static} PlatinumKnife : string <<get>>
    + {static} PlatinumOre : string <<get>>
    + {static} PlatinumPickaxe : string <<get>>
    + {static} PlatinumSickle : string <<get>>
    + {static} PlatinumSpear : string <<get>>
    + {static} PlayerTrackerModule : string <<get>>
    + {static} PoisonArrow : string <<get>>
    + {static} PoisonedAnimalBait : string <<get>>
    + {static} PoisonPaste : string <<get>>
    + {static} PoisonSack : string <<get>>
    + {static} PolarBearArmsArmor : string <<get>>
    + {static} PolarBearChestArmor : string <<get>>
    + {static} PolarBearFeetArmor : string <<get>>
    + {static} PolarBearHead : string <<get>>
    + {static} PolarBearHeadArmor : string <<get>>
    + {static} PolarBearLegsArmor : string <<get>>
    + {static} PolarBearPelt : string <<get>>
    + {static} PolarBearTrophy : string <<get>>
    + {static} PortableBeacon : string <<get>>
    + {static} PotbellyStove : string <<get>>
    + {static} Pumpkin : string <<get>>
    + {static} PumpkinBread : string <<get>>
    + {static} Radar : string <<get>>
    + {static} RainReservoir : string <<get>>
    + {static} RawBacon : string <<get>>
    + {static} RawFattyTbone : string <<get>>
    + {static} RawFish : string <<get>>
    + {static} RawGameMeat : string <<get>>
    + {static} RawGiantSteak : string <<get>>
    + {static} RawMeat : string <<get>>
    + {static} RawSoftMeat : string <<get>>
    + {static} RawStringyMeat : string <<get>>
    + {static} RawWhiteMeat : string <<get>>
    + {static} RecurveBow : string <<get>>
    + {static} ReedFlower : string <<get>>
    + {static} RefinedGold : string <<get>>
    + {static} RefinedWood : string <<get>>
    + {static} Refrigerator : string <<get>>
    + {static} ReinforcedDoor : string <<get>>
    + {static} ReinforcedLadder : string <<get>>
    + {static} ReinforcedRailing : string <<get>>
    + {static} ReinforcedTrapdoor : string <<get>>
    + {static} ReinforcedWindow : string <<get>>
    + {static} RifleRound : string <<get>>
    + {static} RipeCoconut : string <<get>>
    + {static} RoastSquash : string <<get>>
    + {static} RoastVegetables : string <<get>>
    + {static} Rope : string <<get>>
    + {static} SandwormArrow : string <<get>>
    + {static} SandwormBow : string <<get>>
    + {static} SandwormKnife : string <<get>>
    + {static} SandwormScale : string <<get>>
    + {static} SandwormSpear : string <<get>>
    + {static} ScorpionHedgehog : string <<get>>
    + {static} ScorpionPincerTrap : string <<get>>
    + {static} ShengongAkiraHammer : string <<get>>
    + {static} ShengongDaokouKnife : string <<get>>
    + {static} ShengongDidaSpear : string <<get>>
    + {static} ShengongDongPickaxe : string <<get>>
    + {static} ShengongGongBuSpear : string <<get>>
    + {static} ShengongHeikeAxe : string <<get>>
    + {static} ShengongHuluCanteen : string <<get>>
    + {static} ShengongJiBow : string <<get>>
    + {static} ShengongJijingBow : string <<get>>
    + {static} ShengongJijuSpear : string <<get>>
    + {static} ShengongJushiPickaxe : string <<get>>
    + {static} ShengongKuangPickaxe : string <<get>>
    + {static} ShengongLieAxe : string <<get>>
    + {static} ShengongLiweiO2Tank : string <<get>>
    + {static} ShengongQieKnife : string <<get>>
    + {static} ShengongSenAxe : string <<get>>
    + {static} ShengongShuiKnife : string <<get>>
    + {static} ShengongSichouKnife : string <<get>>
    + {static} ShengongSuiShiPickaxe : string <<get>>
    + {static} ShengongTetsuoHammer : string <<get>>
    + {static} ShengongWenheArrow : string <<get>>
    + {static} ShengongXingxingSpear : string <<get>>
    + {static} ShengongYeyingBandage : string <<get>>
    + {static} ShengongZhangHuBow : string <<get>>
    + {static} Shotgun : string <<get>>
    + {static} Shovel : string <<get>>
    + {static} SilicaOre : string <<get>>
    + {static} SkinningBench : string <<get>>
    + {static} SmallInteriorWoodCrate : string <<get>>
    + {static} SmallIronCrate : string <<get>>
    + {static} SmallWoodCrate : string <<get>>
    + {static} SmallWoodSign : string <<get>>
    + {static} SmokeGrenade : string <<get>>
    + {static} SnowLeopardHead : string <<get>>
    + {static} SnowLeopardTrophy : string <<get>>
    + {static} SolarPanel : string <<get>>
    + {static} SoyBean : string <<get>>
    + {static} SoyBeanStir_Fry : string <<get>>
    + {static} Splint : string <<get>>
    + {static} SpoiledMeat : string <<get>>
    + {static} SpoiledPlants : string <<get>>
    + {static} Sponge : string <<get>>
    + {static} Squash : string <<get>>
    + {static} ST_700ArmsArmor : string <<get>>
    + {static} ST_700ChestArmor : string <<get>>
    + {static} ST_700FeetArmor : string <<get>>
    + {static} ST_700HeadArmor : string <<get>>
    + {static} ST_700LegsArmor : string <<get>>
    + {static} Stamina : string <<get>>
    + {static} StaminaBuffPaste : string <<get>>
    + {static} StaminaConsumptionPaste : string <<get>>
    + {static} StaminaRegenerationPaste : string <<get>>
    + {static} StaminaRestorationPaste : string <<get>>
    + {static} SteelAxe : string <<get>>
    + {static} SteelBloom : string <<get>>
    + {static} SteelBolt : string <<get>>
    + {static} SteelHammer : string <<get>>
    + {static} SteelIngot : string <<get>>
    + {static} SteelKnife : string <<get>>
    + {static} SteelPickaxe : string <<get>>
    + {static} SteelRebar : string <<get>>
    + {static} SteelScrew : string <<get>>
    + {static} SteelSpear : string <<get>>
    + {static} Stew : string <<get>>
    + {static} Stick : string <<get>>
    + {static} Stone : string <<get>>
    + {static} StoneArrow : string <<get>>
    + {static} StoneAxe : string <<get>>
    + {static} StoneBeam : string <<get>>
    + {static} StoneFloor : string <<get>>
    + {static} StoneFloorTrapdoor : string <<get>>
    + {static} StoneFrame : string <<get>>
    + {static} StoneFurnace : string <<get>>
    + {static} StoneHalfpieces : string <<get>>
    + {static} StoneHalfpitches : string <<get>>
    + {static} StoneKnife : string <<get>>
    + {static} StonePickaxe : string <<get>>
    + {static} StonePile : string <<get>>
    + {static} StoneRamp : string <<get>>
    + {static} StoneRoof : string <<get>>
    + {static} StoneRoofCorner : string <<get>>
    + {static} StoneStairs : string <<get>>
    + {static} StoneWall : string <<get>>
    + {static} StoneWallAngled : string <<get>>
    + {static} StrengthBoostModule : string <<get>>
    + {static} Sulfur : string <<get>>
    + {static} SurvivalBackpack : string <<get>>
    + {static} SutureKit : string <<get>>
    + {static} SweetcornSoup : string <<get>>
    + {static} TaxidermyKnife : string <<get>>
    + {static} Tea : string <<get>>
    + {static} TextilesBench : string <<get>>
    + {static} ThatchBeam : string <<get>>
    + {static} ThatchDoor : string <<get>>
    + {static} ThatchFloor : string <<get>>
    + {static} ThatchFloorTrapdoor : string <<get>>
    + {static} ThatchHalfpieces : string <<get>>
    + {static} ThatchHalfpitches : string <<get>>
    + {static} ThatchLadder : string <<get>>
    + {static} ThatchRailing : string <<get>>
    + {static} ThatchRamp : string <<get>>
    + {static} ThatchRoof : string <<get>>
    + {static} ThatchRoofCorner : string <<get>>
    + {static} ThatchStairs : string <<get>>
    + {static} ThatchTrapdoor : string <<get>>
    + {static} ThatchWall : string <<get>>
    + {static} ThatchWallAngled : string <<get>>
    + {static} ThatchWindow : string <<get>>
    + {static} Thermos : string <<get>>
    + {static} TitaniumArrow : string <<get>>
    + {static} TitaniumAxe : string <<get>>
    + {static} TitaniumBolt : string <<get>>
    + {static} TitaniumHammer : string <<get>>
    + {static} TitaniumIngot : string <<get>>
    + {static} TitaniumKnife : string <<get>>
    + {static} TitaniumOre : string <<get>>
    + {static} TitaniumPickaxe : string <<get>>
    + {static} TitaniumSickle : string <<get>>
    + {static} TitaniumSpear : string <<get>>
    + {static} TreeSap : string <<get>>
    + {static} TrophyBench : string <<get>>
    + {static} Ultrameal : string <<get>>
    + {static} VegetablePie : string <<get>>
    + {static} WallTorch : string <<get>>
    + {static} Water : string <<get>>
    + {static} WaterConsumptionPaste : string <<get>>
    + {static} Watermelon : string <<get>>
    + {static} WaterPipeTool : string <<get>>
    + {static} WaterPump : string <<get>>
    + {static} Waterskin : string <<get>>
    + {static} WaterSources : string <<get>>
    + {static} WaterSprinkler : string <<get>>
    + {static} Wheat : string <<get>>
    + {static} WildBerry : string <<get>>
    + {static} WildSalad : string <<get>>
    + {static} Wine : string <<get>>
    + {static} WineBottle : string <<get>>
    + {static} Wood : string <<get>>
    + {static} WoodBeam : string <<get>>
    + {static} WoodBed : string <<get>>
    + {static} WoodBow : string <<get>>
    + {static} WoodChair : string <<get>>
    + {static} WoodComposter : string <<get>>
    + {static} WoodCropPlot : string <<get>>
    + {static} WoodCupboard : string <<get>>
    + {static} WoodDoor : string <<get>>
    + {static} WoodFloor : string <<get>>
    + {static} WoodFloorTrapdoor : string <<get>>
    + {static} WoodHalfpieces : string <<get>>
    + {static} WoodHalfpitches : string <<get>>
    + {static} WoodLadder : string <<get>>
    + {static} WoodPile : string <<get>>
    + {static} WoodRagTorch : string <<get>>
    + {static} WoodRailing : string <<get>>
    + {static} WoodRamp : string <<get>>
    + {static} WoodRepairHammer : string <<get>>
    + {static} WoodRoof : string <<get>>
    + {static} WoodRoofCorner : string <<get>>
    + {static} WoodSpear : string <<get>>
    + {static} WoodStairs : string <<get>>
    + {static} WoodTable : string <<get>>
    + {static} WoodTorch : string <<get>>
    + {static} WoodTrapdoor : string <<get>>
    + {static} WoodWall : string <<get>>
    + {static} WoodWallAngled : string <<get>>
    + {static} WoodWindow : string <<get>>
    + {static} WorkShop : string <<get>>
    + {static} WorkshopRepairKit : string <<get>>
    + {static} WorkshopRepairKitBundle : string <<get>>
    + {static} WormScale : string <<get>>
    + {static} Yeast : string <<get>>
    + {static} YoungCoconut : string <<get>>
}
@enduml
