//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IcarusLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class miscellaneous {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal miscellaneous() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IcarusLib.Properties.miscellaneous", typeof(miscellaneous).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ammo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ammo {
            get {
                return ResourceManager.GetString("Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AnimalHead に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnimalHead {
            get {
                return ResourceManager.GetString("AnimalHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Armors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Armors {
            get {
                return ResourceManager.GetString("Armors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Axe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Axe {
            get {
                return ResourceManager.GetString("Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Benches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Benches {
            get {
                return ResourceManager.GetString("Benches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Bow {
            get {
                return ResourceManager.GetString("Bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Building Pieces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BuildingPieces {
            get {
                return ResourceManager.GetString("BuildingPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Climate Control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClimateControl {
            get {
                return ResourceManager.GetString("ClimateControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consumables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Consumables {
            get {
                return ResourceManager.GetString("Consumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cooking Benches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CookingBenches {
            get {
                return ResourceManager.GetString("CookingBenches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Crafting Benches に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CraftingBenches {
            get {
                return ResourceManager.GetString("CraftingBenches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deployables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Deployables {
            get {
                return ResourceManager.GetString("Deployables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drinks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Drinks {
            get {
                return ResourceManager.GetString("Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Environsuits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Environsuits {
            get {
                return ResourceManager.GetString("Environsuits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firearms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Firearms {
            get {
                return ResourceManager.GetString("Firearms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Food に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hammer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hammer {
            get {
                return ResourceManager.GetString("Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ingot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ingot {
            get {
                return ResourceManager.GetString("Ingot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Knife に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Knife {
            get {
                return ResourceManager.GetString("Knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Materials に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medicine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modules に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sourcing locally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotToBeCrafted {
            get {
                return ResourceManager.GetString("NotToBeCrafted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ore に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ore {
            get {
                return ResourceManager.GetString("Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pickaxe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pickaxe {
            get {
                return ResourceManager.GetString("Pickaxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resources に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sickle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sickle {
            get {
                return ResourceManager.GetString("Sickle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Spear {
            get {
                return ResourceManager.GetString("Spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weapons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Workshop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
    }
}
